Homework 1 - Hristiyan Radev 25
svetlin-mladenov/software-engineering-2223 pull request #17
Opened 2022-11-03 19:41 UTC by Hristiyyann

2022-11-05 14:24 UTC, svetlin-mladenov requested changes

2022-11-05 14:24 UTC, svetlin-mladenov commented on .vscode/settings.json
> +{
git rm this file. I don't care about your vscode settings.

2022-11-05 14:24 UTC, svetlin-mladenov commented on homework/12_B/25_Hristiyan/homework1/circles.py
> +    if distance == radii_subtraction ==  0: return "They are equal"
Can you refactor the code to return enum instead of a string. Or at least move these hardcoded strings to global variables

2022-11-05 14:24 UTC, svetlin-mladenov commented on homework/12_B/25_Hristiyan/homework1/circles.py
> +    elif distance == radii_sum: return "They touch externally"
The pythonic way is to always put the return statement on a new line.

2022-11-06 11:52 UTC, Hristiyyann reviewed
Нещата, които сте посочили за оправяне, са вече оправени.

2022-11-13 11:45 UTC, merged