Added Homework 1
svetlin-mladenov/software-engineering-2223 pull request #3
Opened 2022-10-28 11:53 UTC by Hrist0ff

2022-11-05 15:22 UTC, svetlin-mladenov requested changes

2022-11-05 15:22 UTC, svetlin-mladenov commented on homework/12_B/02_Aleksandar/homework1/circle.py
> +        return Intersection.INVALID.name # INVALID
You can just return `Intersection.INVALID`

2022-11-05 15:22 UTC, svetlin-mladenov commented on homework/12_B/02_Aleksandar/homework1/circle.py
> +        return Intersection.INTERSECT.name # INTERSECT
No need for the comments. The code make it clear.

2022-11-05 15:22 UTC, svetlin-mladenov commented on homework/12_B/02_Aleksandar/homework1/circle.py
> +    print (self.x)
These are obviously debug statements. Please remove them.

2022-11-05 15:22 UTC, svetlin-mladenov commented on homework/12_B/02_Aleksandar/homework1/test_circle.py
> +    assert C1.check(C5) == 'TOUCHING'
Can you add more test cases. For example when two circles are touching on the inside.

2022-11-06 13:22 UTC, Hrist0ff reviewed
changes

2022-11-13 11:52 UTC, merged